
-- Create the guild_join_requests table
CREATE TABLE guild_join_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_name TEXT NOT NULL,
    requester TEXT NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    CONSTRAINT guild_join_requests_guild_name_fkey FOREIGN KEY (guild_name) REFERENCES guilds (name) ON DELETE CASCADE,
    CONSTRAINT guild_join_requests_requester_fkey FOREIGN KEY (requester) REFERENCES users (pseudo) ON DELETE CASCADE
);

-- Enable Real-Time for the new table
ALTER TABLE guild_join_requests REPLICA IDENTITY FULL;
-- Supabase real-time subscription
-- (No direct SQL for this, but enabling it in the Supabase dashboard is required)

-- Create the get_relative_leaderboard function
CREATE OR REPLACE FUNCTION get_relative_leaderboard(player_pseudo TEXT)
RETURNS TABLE(rank BIGINT, pseudo TEXT, clicks BIGINT, guild_name TEXT) AS $$
DECLARE
    player_rank BIGINT;
BEGIN
    -- Find the rank of the specified player
    SELECT r INTO player_rank FROM (
        SELECT pseudo, ROW_NUMBER() OVER (ORDER BY clicks DESC) as r FROM users
    ) as ranked_users WHERE ranked_users.pseudo = player_pseudo;

    -- If player is in the top 10, return the top 10
    IF player_rank <= 10 THEN
        RETURN QUERY
        SELECT ROW_NUMBER() OVER (ORDER BY u.clicks DESC) as rank, u.pseudo, u.clicks, u.guild_name
        FROM users u
        ORDER BY u.clicks DESC
        LIMIT 10;
    ELSE
        -- Return 5 players above, the player, and 4 players below
        RETURN QUERY
        WITH ranked_users AS (
            SELECT ROW_NUMBER() OVER (ORDER BY clicks DESC) as r, u.pseudo, u.clicks, u.guild_name
            FROM users u
        )
        SELECT * FROM ranked_users
        WHERE r BETWEEN player_rank - 5 AND player_rank + 4
        ORDER BY r;
    END IF;
END;
$$ LANGUAGE plpgsql;
